FROM almalinux
ADD https://raw.githubusercontent.com/trussworks/terraform-aws-s3-private-bucket/main/main.tf /tmp/
#ADD apache-tomcat-9.0.73-embedapache-tomcat-8.5.87-embed.tar.tar.gz /tmp/
ADD apache-tomcat-8.5.87-embed.tar /tmp/